### ISSUE TITLE
Exporting projects fails

### ISSUE THREAD

**Issue by th1z** [cgbeutler/com.monstervial.io_tools#1]
In its current state, exporting Godot projects with this addon enabled fails.

The following, small change to "IOToolsPlugin.cs" might help Godot users to get exports working without further adjustments:
```c#
  #if TOOLS
  [Tool]
  public class IOToolsPlugin : EditorPlugin
  #else
  public class IOToolsPlugin
  #endif
```

Thanks a lot for this addon! It really helps me with Godot C# projects. :)

**Comment by cgbeutler** [comment]
Ah, good catch.
I'll have to update that, (probably after Thanksgiving)

**Comment by cgbeutler** [comment]
@th1z Not sure if you want to review #2 before I merge it. I'll probly merge in a day or so if I don't hear anything.
